package:
  name: umbriel
  version: 0.1.0
  epoch: 0
  description: "A Wayland compositor built on wlroots"
  url: https://noctalia.dev/
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/noctalia-dev/umbriel
      expected-commit: f976de59e196fc74bce36c6b76e7ccd209e50839

